apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
  - name: it-request-backend
    count: 1
labels:
  - includeSelectors: true
    pairs:
      app: it-request-backend
configMapGenerator:
  - behavior: replace
    envs:
      - .env
    name: it-request-backend-config
    namespace: staging
resources:
  - ../../base
images:
  - name: tanpiyangkoon/it-request-backend
    newTag: "staging-f8f8dfa596e-16"
