apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: it-request-backend
  namespace: "staging"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-request-backend
  template:
    metadata:
      labels:
        app: it-request-backend
    spec:
      containers:
      - name: it-request-backend
        image: tanpiyangkoon/it-request-backend
        port:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: it-request-backend-config
              key: NODE_ENV

    