apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
- includeSelectors: true
  pairs:
    app: it-request-backend
configMapGenerator:
  - name: it-request-backend-config
    namespace: staging
    envs: [.env]
    behavior: create