apiVersion: "v1"
kind: "Service"
metadata:
  name: "it-request-backend"
  namespace: "staging"
spec:
  selector:
    app: "it-request-backend"
  ports:
  - protocol: "TCP"
    port: 3001
    targetPort: 3001
  type: "ClusterIP"





